FROM python:3.13-slim

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y --no-install-recommends iproute2 \
    && rm -rf /var/lib/apt/lists

# Instala todas las dependencias de Python
# For security functions
RUN pip install cryptography

# El resto de la imagen se construye encima de esta base
