FROM python:3.13-slim

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y --no-install-recommends iproute2 \
    && rm -rf /var/lib/apt/lists

# Instala todas las dependencias de Python
# For security functions
RUN pip install cryptography

#for gui
RUN pip install PyQt6

# El resto de la imagen se construye encima de esta base

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libxkbcommon0 libx11-6 libxcb1 libxext6 libglib2.0-0 libgl1 \
    libpulse0 xdg-utils fonts-dejavu-core \
 && rm -rf /var/lib/apt/lists/*